procedure InitializeComponent;
    begin
        var resources: System.ComponentModel.ComponentResourceManager := new System.ComponentModel.ComponentResourceManager(typeof(Form1));
        self.button1 := new System.Windows.Forms.Button();
        self.button2 := new System.Windows.Forms.Button();
        self.button3 := new System.Windows.Forms.Button();
        self.button4 := new System.Windows.Forms.Button();
        self.button5 := new System.Windows.Forms.Button();
        self.button6 := new System.Windows.Forms.Button();
        self.button7 := new System.Windows.Forms.Button();
        self.button8 := new System.Windows.Forms.Button();
        self.button9 := new System.Windows.Forms.Button();
        self.button10 := new System.Windows.Forms.Button();
        self.button11 := new System.Windows.Forms.Button();
        self.button12 := new System.Windows.Forms.Button();
        self.button14 := new System.Windows.Forms.Button();
        self.button15 := new System.Windows.Forms.Button();
        self.button16 := new System.Windows.Forms.Button();
        self.textBox1 := new System.Windows.Forms.TextBox();
        self.button13 := new System.Windows.Forms.Button();
        self.button17 := new System.Windows.Forms.Button();
        self.button18 := new System.Windows.Forms.Button();
        self.button20 := new System.Windows.Forms.Button();
        self.SuspendLayout();
        // 
        // button1
        // 
        self.button1.BackColor := System.Drawing.Color.WhiteSmoke;
        self.button1.Cursor := System.Windows.Forms.Cursors.Default;
        self.button1.Font := new System.Drawing.Font('Segoe UI Variable Display Semil', 19.8000011, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, (System.Byte(204)));
        self.button1.Location := new System.Drawing.Point(-1, 298);
        self.button1.Name := 'button1';
        self.button1.Size := new System.Drawing.Size(72, 72);
        self.button1.TabIndex := 0;
        self.button1.Text := '1';
        self.button1.UseVisualStyleBackColor := false;
        self.button1.Click += button1_Click;
        // 
        // button2
        // 
        self.button2.BackColor := System.Drawing.Color.WhiteSmoke;
        self.button2.Cursor := System.Windows.Forms.Cursors.Default;
        self.button2.Font := new System.Drawing.Font('Segoe UI Variable Display Semil', 19.8000011, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, (System.Byte(204)));
        self.button2.Location := new System.Drawing.Point(70, 298);
        self.button2.Name := 'button2';
        self.button2.Size := new System.Drawing.Size(72, 72);
        self.button2.TabIndex := 1;
        self.button2.Text := '2';
        self.button2.UseVisualStyleBackColor := false;
        self.button2.Click += button2_Click;
        // 
        // button3
        // 
        self.button3.BackColor := System.Drawing.Color.WhiteSmoke;
        self.button3.Cursor := System.Windows.Forms.Cursors.Default;
        self.button3.Font := new System.Drawing.Font('Segoe UI Variable Display Semil', 19.8000011, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, (System.Byte(204)));
        self.button3.Location := new System.Drawing.Point(141, 298);
        self.button3.Name := 'button3';
        self.button3.Size := new System.Drawing.Size(72, 72);
        self.button3.TabIndex := 2;
        self.button3.Text := '3';
        self.button3.UseVisualStyleBackColor := false;
        self.button3.Click += button3_Click;
        // 
        // button4
        // 
        self.button4.BackColor := System.Drawing.Color.WhiteSmoke;
        self.button4.Cursor := System.Windows.Forms.Cursors.Default;
        self.button4.Font := new System.Drawing.Font('Segoe UI Variable Display Semil', 19.8000011, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, (System.Byte(204)));
        self.button4.Location := new System.Drawing.Point(-1, 227);
        self.button4.Name := 'button4';
        self.button4.Size := new System.Drawing.Size(72, 72);
        self.button4.TabIndex := 3;
        self.button4.Text := '4';
        self.button4.UseVisualStyleBackColor := false;
        self.button4.Click += button4_Click;
        // 
        // button5
        // 
        self.button5.BackColor := System.Drawing.Color.WhiteSmoke;
        self.button5.Cursor := System.Windows.Forms.Cursors.Default;
        self.button5.Font := new System.Drawing.Font('Segoe UI Variable Display Semil', 19.8000011, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, (System.Byte(204)));
        self.button5.Location := new System.Drawing.Point(70, 227);
        self.button5.Name := 'button5';
        self.button5.Size := new System.Drawing.Size(72, 72);
        self.button5.TabIndex := 4;
        self.button5.Text := '5';
        self.button5.UseVisualStyleBackColor := false;
        self.button5.Click += button5_Click;
        // 
        // button6
        // 
        self.button6.BackColor := System.Drawing.Color.WhiteSmoke;
        self.button6.Cursor := System.Windows.Forms.Cursors.Default;
        self.button6.Font := new System.Drawing.Font('Segoe UI Variable Display Semil', 19.8000011, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, (System.Byte(204)));
        self.button6.Location := new System.Drawing.Point(141, 227);
        self.button6.Name := 'button6';
        self.button6.Size := new System.Drawing.Size(72, 72);
        self.button6.TabIndex := 5;
        self.button6.Text := '6';
        self.button6.UseVisualStyleBackColor := false;
        self.button6.Click += button6_Click;
        // 
        // button7
        // 
        self.button7.BackColor := System.Drawing.Color.WhiteSmoke;
        self.button7.Cursor := System.Windows.Forms.Cursors.Default;
        self.button7.Font := new System.Drawing.Font('Segoe UI Variable Display Semil', 19.8000011, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, (System.Byte(204)));
        self.button7.Location := new System.Drawing.Point(70, 156);
        self.button7.Name := 'button7';
        self.button7.Size := new System.Drawing.Size(72, 72);
        self.button7.TabIndex := 6;
        self.button7.Text := '8';
        self.button7.UseVisualStyleBackColor := false;
        self.button7.Click += button7_Click;
        // 
        // button8
        // 
        self.button8.BackColor := System.Drawing.Color.WhiteSmoke;
        self.button8.Cursor := System.Windows.Forms.Cursors.Default;
        self.button8.Font := new System.Drawing.Font('Segoe UI Variable Display Semil', 19.8000011, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, (System.Byte(204)));
        self.button8.Location := new System.Drawing.Point(-1, 369);
        self.button8.Name := 'button8';
        self.button8.Size := new System.Drawing.Size(143, 72);
        self.button8.TabIndex := 7;
        self.button8.Text := '0';
        self.button8.UseVisualStyleBackColor := false;
        self.button8.Click += button8_Click;
        // 
        // button9
        // 
        self.button9.BackColor := System.Drawing.Color.WhiteSmoke;
        self.button9.Cursor := System.Windows.Forms.Cursors.Default;
        self.button9.Font := new System.Drawing.Font('Segoe UI Variable Display Semil', 19.8000011, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, (System.Byte(204)));
        self.button9.Location := new System.Drawing.Point(141, 156);
        self.button9.Name := 'button9';
        self.button9.Size := new System.Drawing.Size(72, 72);
        self.button9.TabIndex := 7;
        self.button9.Text := '9';
        self.button9.UseVisualStyleBackColor := false;
        self.button9.Click += button9_Click;
        // 
        // button10
        // 
        self.button10.BackColor := System.Drawing.Color.WhiteSmoke;
        self.button10.Cursor := System.Windows.Forms.Cursors.Default;
        self.button10.Font := new System.Drawing.Font('Segoe UI Variable Display Semil', 19.8000011, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, (System.Byte(204)));
        self.button10.Location := new System.Drawing.Point(-1, 156);
        self.button10.Name := 'button10';
        self.button10.Size := new System.Drawing.Size(72, 72);
        self.button10.TabIndex := 8;
        self.button10.Text := '7';
        self.button10.UseVisualStyleBackColor := false;
        self.button10.Click += button10_Click;
        // 
        // button11
        // 
        self.button11.BackColor := System.Drawing.Color.Gainsboro;
        self.button11.Font := new System.Drawing.Font('Segoe UI Variable Display', 19.8000011, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, (System.Byte(204)));
        self.button11.ForeColor := System.Drawing.Color.Red;
        self.button11.Location := new System.Drawing.Point(-1, 85);
        self.button11.Name := 'button11';
        self.button11.Size := new System.Drawing.Size(72, 72);
        self.button11.TabIndex := 9;
        self.button11.Text := 'C';
        self.button11.UseVisualStyleBackColor := false;
        self.button11.Click += button11_Click;
        // 
        // button12
        // 
        self.button12.BackColor := System.Drawing.Color.Gainsboro;
        self.button12.Font := new System.Drawing.Font('Segoe UI Variable Display', 19.8000011, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, (System.Byte(204)));
        self.button12.Location := new System.Drawing.Point(213, 298);
        self.button12.Name := 'button12';
        self.button12.Size := new System.Drawing.Size(72, 72);
        self.button12.TabIndex := 10;
        self.button12.Text := '+';
        self.button12.UseVisualStyleBackColor := false;
        self.button12.Click += button12_Click;
        // 
        // button14
        // 
        self.button14.BackColor := System.Drawing.Color.Gainsboro;
        self.button14.Font := new System.Drawing.Font('Segoe UI Variable Display', 19.8000011, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, (System.Byte(204)));
        self.button14.Location := new System.Drawing.Point(213, 85);
        self.button14.Name := 'button14';
        self.button14.Size := new System.Drawing.Size(72, 72);
        self.button14.TabIndex := 12;
        self.button14.Text := '÷';
        self.button14.UseVisualStyleBackColor := false;
        self.button14.Click += button14_Click;
        // 
        // button15
        // 
        self.button15.BackColor := System.Drawing.Color.Gainsboro;
        self.button15.Font := new System.Drawing.Font('Segoe UI Variable Display', 19.8000011, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, (System.Byte(204)));
        self.button15.Location := new System.Drawing.Point(213, 156);
        self.button15.Name := 'button15';
        self.button15.Size := new System.Drawing.Size(72, 72);
        self.button15.TabIndex := 13;
        self.button15.Text := '×';
        self.button15.UseVisualStyleBackColor := false;
        self.button15.Click += button15_Click;
        // 
        // button16
        // 
        self.button16.BackColor := System.Drawing.Color.Gainsboro;
        self.button16.Font := new System.Drawing.Font('Segoe UI Variable Display', 19.8000011, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, (System.Byte(204)));
        self.button16.Location := new System.Drawing.Point(213, 369);
        self.button16.Name := 'button16';
        self.button16.Size := new System.Drawing.Size(72, 72);
        self.button16.TabIndex := 14;
        self.button16.Text := '=';
        self.button16.UseVisualStyleBackColor := false;
        self.button16.Click += button16_Click;
        // 
        // textBox1
        // 
        self.textBox1.BackColor := System.Drawing.Color.Gray;
        self.textBox1.Font := new System.Drawing.Font('Segoe UI Variable Display Semil', 36, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, (System.Byte(204)));
        self.textBox1.ForeColor := System.Drawing.Color.White;
        self.textBox1.Location := new System.Drawing.Point(-1, -1);
        self.textBox1.Multiline := true;
        self.textBox1.Name := 'textBox1';
        self.textBox1.Size := new System.Drawing.Size(286, 87);
        self.textBox1.TabIndex := 15;
        // 
        // button13
        // 
        self.button13.BackColor := System.Drawing.Color.Gainsboro;
        self.button13.Font := new System.Drawing.Font('Segoe UI Variable Display', 19.8000011, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, (System.Byte(204)));
        self.button13.Location := new System.Drawing.Point(213, 227);
        self.button13.Name := 'button13';
        self.button13.Size := new System.Drawing.Size(72, 72);
        self.button13.TabIndex := 11;
        self.button13.Text := '-';
        self.button13.UseVisualStyleBackColor := false;
        self.button13.Click += button13_Click;
        // 
        // button17
        // 
        self.button17.BackColor := System.Drawing.Color.Gainsboro;
        self.button17.Font := new System.Drawing.Font('Segoe UI Variable Display', 19.8000011, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, (System.Byte(204)));
        self.button17.Location := new System.Drawing.Point(141, 85);
        self.button17.Name := 'button17';
        self.button17.Size := new System.Drawing.Size(72, 72);
        self.button17.TabIndex := 16;
        self.button17.Text := 'x²';
        self.button17.UseVisualStyleBackColor := false;
        self.button17.Click += ButtonSquareClick;
        // 
        // button18
        // 
        self.button18.BackColor := System.Drawing.Color.Gainsboro;
        self.button18.Font := new System.Drawing.Font('Segoe UI Variable Display', 19.8000011, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, (System.Byte(204)));
        self.button18.Location := new System.Drawing.Point(70, 85);
        self.button18.Name := 'button18';
        self.button18.Size := new System.Drawing.Size(72, 72);
        self.button18.TabIndex := 17;
        self.button18.Text := '±';
        self.button18.UseVisualStyleBackColor := false;
        self.button18.Click += ButtonReverseClick;
        // 
        // button20
        // 
        self.button20.BackColor := System.Drawing.Color.WhiteSmoke;
        self.button20.Cursor := System.Windows.Forms.Cursors.Default;
        self.button20.Font := new System.Drawing.Font('Segoe UI Variable Display Semil', 19.8000011, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, (System.Byte(204)));
        self.button20.Location := new System.Drawing.Point(141, 369);
        self.button20.Name := 'button20';
        self.button20.Size := new System.Drawing.Size(72, 72);
        self.button20.TabIndex := 19;
        self.button20.Text := '<';
        self.button20.UseVisualStyleBackColor := false;
        self.button20.Click += ButtonBackspaceClick;
        // 
        // Form1
        // 
        self.ClientSize := new System.Drawing.Size(286, 441);
        self.Controls.Add(self.button20);
        self.Controls.Add(self.button14);
        self.Controls.Add(self.button18);
        self.Controls.Add(self.button11);
        self.Controls.Add(self.button17);
        self.Controls.Add(self.textBox1);
        self.Controls.Add(self.button16);
        self.Controls.Add(self.button15);
        self.Controls.Add(self.button13);
        self.Controls.Add(self.button12);
        self.Controls.Add(self.button10);
        self.Controls.Add(self.button9);
        self.Controls.Add(self.button8);
        self.Controls.Add(self.button7);
        self.Controls.Add(self.button6);
        self.Controls.Add(self.button5);
        self.Controls.Add(self.button4);
        self.Controls.Add(self.button3);
        self.Controls.Add(self.button2);
        self.Controls.Add(self.button1);
        self.Font := new System.Drawing.Font('Microsoft Sans Serif', 14);
        self.Icon := (System.Drawing.Icon(resources.GetObject('$this.Icon')));
        self.Name := 'Form1';
        self.Text := 'Калькулятор (by Abdulbasirov)';
        self.Load += Form1_Load;
        self.ResumeLayout(false);
        self.PerformLayout();
    end;
